Security fix for addon-resizer v1.8.16
platform9/cluster-autoscaler pull request #1
Opened 2023-03-21 13:07 UTC by ShaunakJoshi1407

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-03-23 05:33 UTC, cruizen requested changes
We need to revisit, change where the Docker image is published.

2023-03-23 05:33 UTC, cruizen commented on addon-resizer/Makefile
>  REGISTRY = gcr.io/k8s-staging-autoscaling
Now that we have forked from the upstream repo, we should change the registry and tag.

2023-03-23 11:37 UTC, ShaunakJoshi1407 commented
__

2023-03-23 11:37 UTC, closed without merging

2023-04-05 09:05 UTC, cruizen commented
> __

Why did we close the PR? Can we add any detail?

2023-04-05 10:23 UTC, ShaunakJoshi1407 commented
> > __
> 
> Why did we close the PR? Can we add any detail?

Closing this PR out and raised a new PR here: https://github.com/platform9/cluster-autoscaler/pull/2 that includes pushing the image to Platform9 dockerhub.